name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint:check
      - run: bun run build
        env:
          VITE_TEST: 1
      - run: bun run test
      - name: Start local dev
        run: bun run dev > /tmp/stdout.log 2> /tmp/stderr.log &
      - name: Test local dev
        run: |
          sleep 2
          curl --retry-connrefused --retry 4 http://localhost:5173
